# rcov Copyright (c) 2004-2006 Mauricio Fernandez <mfp@acm.org>
#
# See LEGAL and LICENSE for licensing information.

# NOTE: if you're reading this in the XHTML code coverage report generated by
# rcov, you'll notice that only code inside methods is reported as covered,
# very much like what happens when you run it with --test-unit-only.
# This is due to the fact that we're running rcov on itself: the code below is
# already loaded before coverage tracing is activated, so only code inside
# methods is actually executed under rcov's inspection.

require File.expand_path(File.join(File.dirname(__FILE__), 'rcov', 'call_site_analyzer'))
require File.expand_path(File.join(File.dirname(__FILE__), 'rcov', 'coverage_info'))
require File.expand_path(File.join(File.dirname(__FILE__), 'rcov', 'code_coverage_analyzer'))
require File.expand_path(File.join(File.dirname(__FILE__), 'rcov', 'differential_analyzer'))
require File.expand_path(File.join(File.dirname(__FILE__), 'rcov', 'file_statistics'))
require File.expand_path(File.join(File.dirname(__FILE__), 'rcov', 'version'))

SCRIPT_LINES__ = {} unless defined? SCRIPT_LINES__

module Rcov

  autoload :RCOV__, "rcov/lowlevel.rb"

end
